# Generated by Django 2.1.5 on 2019-01-24 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketballEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_time', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('2PT', 'پرتاب دو امتیازی'), ('3PT', 'پرتاب سه امتیازی'), ('E', 'خطا'), ('R', 'ریباند')], max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasketballGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_team_score', models.IntegerField()),
                ('second_team_score', models.IntegerField()),
                ('first_team_percentage_possession', models.IntegerField()),
                ('report', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ('date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasketballLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasketballNonPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_day', models.DateField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=2, max_length=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=2, max_length=5)),
                ('image', models.ImageField(blank=True, upload_to='human_images')),
                ('post', models.CharField(choices=[('C', 'مربی'), ('CH', 'کمک مربی')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasketballPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_day', models.DateField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=2, max_length=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=2, max_length=5)),
                ('image', models.ImageField(blank=True, upload_to='human_images')),
                ('post', models.CharField(choices=[('RB', 'بسکتبالیست چپ'), ('LB', 'بسکتبالیست راست'), ('MB', 'بسکتبالیست اصلی')], max_length=2)),
                ('followers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasketballTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('followers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FootballEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_time', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('G', 'گل'), ('PG', 'پاس گل'), ('YC', 'کارت زرد'), ('RC', 'کارت قرمز'), ('E', 'خطا'), ('P', 'پنالتی'), ('CH', 'تعویض'), ('CO', 'کرنر'), ('SG', 'موقعیت گل')], max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FootballGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_team_score', models.IntegerField()),
                ('second_team_score', models.IntegerField()),
                ('first_team_percentage_possession', models.IntegerField()),
                ('report', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ('date',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FootballLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FootballNonPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_day', models.DateField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=2, max_length=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=2, max_length=5)),
                ('image', models.ImageField(blank=True, upload_to='human_images')),
                ('post', models.CharField(choices=[('C', 'مربی'), ('CH', 'کمک مربی')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FootballPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_day', models.DateField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=2, max_length=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=2, max_length=5)),
                ('image', models.ImageField(blank=True, upload_to='human_images')),
                ('post', models.CharField(choices=[('G', 'دروازه بان'), ('HB', 'هاف بک'), ('HF', 'هاف فرانت')], max_length=2)),
                ('followers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FootballTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('followers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('news', models.ManyToManyField(to='sport.News')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('news', models.ManyToManyField(to='sport.News')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='footballteam',
            name='news',
            field=models.ManyToManyField(to='sport.News'),
        ),
        migrations.AddField(
            model_name='footballplayer',
            name='news',
            field=models.ManyToManyField(to='sport.News'),
        ),
        migrations.AddField(
            model_name='footballplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.FootballTeam'),
        ),
        migrations.AddField(
            model_name='footballnonplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.FootballTeam'),
        ),
        migrations.AddField(
            model_name='footballgame',
            name='teams',
            field=models.ManyToManyField(to='sport.FootballTeam'),
        ),
        migrations.AddField(
            model_name='footballevent',
            name='doer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.FootballPlayer'),
        ),
        migrations.AddField(
            model_name='footballevent',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.FootballGame'),
        ),
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.News'),
        ),
        migrations.AddField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basketballteam',
            name='news',
            field=models.ManyToManyField(to='sport.News'),
        ),
        migrations.AddField(
            model_name='basketballplayer',
            name='news',
            field=models.ManyToManyField(to='sport.News'),
        ),
        migrations.AddField(
            model_name='basketballplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.BasketballTeam'),
        ),
        migrations.AddField(
            model_name='basketballnonplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.BasketballTeam'),
        ),
        migrations.AddField(
            model_name='basketballgame',
            name='teams',
            field=models.ManyToManyField(to='sport.BasketballTeam'),
        ),
        migrations.AddField(
            model_name='basketballevent',
            name='doer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.BasketballPlayer'),
        ),
        migrations.AddField(
            model_name='basketballevent',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.BasketballGame'),
        ),
    ]
