# Generated by Django 2.1.5 on 2019-01-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_news_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('F', 'فوتبال'), ('B', 'بسکتبال')], default='F', max_length=1),
        ),
    ]
