# Generated by Django 2.1.5 on 2019-01-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_news_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketballteam',
            name='news',
        ),
        migrations.RemoveField(
            model_name='footballteam',
            name='news',
        ),
    ]
