# Generated by Django 2.1.5 on 2019-01-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0004_auto_20190124_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketballnonplayer',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='basketballnonplayer',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='basketballplayer',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='basketballplayer',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='footballnonplayer',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='footballnonplayer',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='footballplayer',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='footballplayer',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
