# Generated by Django 2.1.5 on 2019-01-24 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0005_auto_20190124_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballPlayerInFootballGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_player', models.BooleanField(blank=True, null=True)),
                ('time_of_change', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FootballTeamInFootballGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_score', models.IntegerField(blank=True, null=True)),
                ('property_percent', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='basketballgame',
            name='first_team_percentage_possession',
        ),
        migrations.RemoveField(
            model_name='basketballgame',
            name='first_team_score',
        ),
        migrations.RemoveField(
            model_name='basketballgame',
            name='second_team_score',
        ),
        migrations.RemoveField(
            model_name='footballgame',
            name='first_team_percentage_possession',
        ),
        migrations.RemoveField(
            model_name='footballgame',
            name='first_team_score',
        ),
        migrations.RemoveField(
            model_name='footballgame',
            name='second_team_score',
        ),
        migrations.AddField(
            model_name='footballteaminfootballgame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.FootballGame'),
        ),
        migrations.AddField(
            model_name='footballteaminfootballgame',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.FootballTeam'),
        ),
        migrations.AddField(
            model_name='footballplayerinfootballgame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.FootballGame'),
        ),
        migrations.AddField(
            model_name='footballplayerinfootballgame',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport.FootballPlayer'),
        ),
    ]
