# Generated by Django 2.1.5 on 2019-01-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0007_remove_footballgame_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballteaminfootballgame',
            name='situation',
            field=models.CharField(blank=True, choices=[('AW', 'برد'), ('BE', 'مساوی'), ('CL', 'باخت')], max_length=3, null=True),
        ),
    ]
