# Generated by Django 2.1.5 on 2019-01-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0008_footballteaminfootballgame_situation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basketballevent',
            options={'ordering': ('-exact_time',)},
        ),
        migrations.AlterModelOptions(
            name='basketballgame',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='footballevent',
            options={'ordering': ('-exact_time',)},
        ),
        migrations.AlterModelOptions(
            name='footballgame',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='footballteaminfootballgame',
            name='best_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.FootballPlayer'),
        ),
    ]
