# Generated by Django 2.1.5 on 2019-01-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0009_auto_20190125_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='general_images'),
        ),
        migrations.AddField(
            model_name='image',
            name='news',
            field=models.ManyToManyField(blank=True, null=True, to='sport.News'),
        ),
        migrations.AddField(
            model_name='video',
            name='caption',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='general_videos'),
        ),
    ]
