# Generated by Django 2.1.5 on 2019-01-25 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0010_auto_20190125_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='', max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='general_images')),
                ('football_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.FootballGame')),
                ('news', models.ManyToManyField(blank=True, null=True, to='sport.News')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FootballVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(default='', max_length=250)),
                ('video', models.FileField(blank=True, null=True, upload_to='general_videos')),
                ('football_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.FootballGame')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='image',
            name='news',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
