# Generated by Django 2.1.5 on 2019-01-25 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0011_auto_20190125_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Pieces of news'},
        ),
        migrations.AddField(
            model_name='footballleague',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sport.FootballGame'),
        ),
    ]
