# Generated by Django 2.1.5 on 2019-01-28 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0016_auto_20190128_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketballplayer',
            name='news',
        ),
        migrations.RemoveField(
            model_name='footballplayer',
            name='news',
        ),
    ]
