# Generated by Django 2.1.5 on 2019-01-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0019_auto_20190128_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketballteaminbasketballgame',
            old_name='team_score',
            new_name='team_score_Q1',
        ),
        migrations.AddField(
            model_name='basketballteaminbasketballgame',
            name='team_score_Q2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basketballteaminbasketballgame',
            name='team_score_Q3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basketballteaminbasketballgame',
            name='team_score_Q4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basketballevent',
            name='event_type',
            field=models.CharField(choices=[('2PT', 'پرتاب دو امتیازی'), ('3PT', 'پرتاب سه امتیازی'), ('E', 'خطا'), ('R', 'ریباند'), ('P', 'پنالتی'), ('LP', 'از دست دادن پنالتی'), ('CH', 'تعویض')], max_length=3),
        ),
    ]
